[settings]
file_list = "path-to-file-list"
file_path = "path-to-datafiles"
output_location = "path-to-outout-location"
t_start = "start-time"
t_end = "end-time"
experiment_name = "experiment-name"
n_samples = "number-of-samples"
